In [1]:
import numpy as np
from dataset import CoronalFieldDataset
import visualization_tools

/home/ubuntu/micromamba/envs/coronal-diffusion-modeling/lib/python3.12/site-packages/ai/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources


# Test Visualization Tools

In [2]:

def read_sh_coefficients(dataset_path, index):
    ds = CoronalFieldDataset(dataset_path)
    arr = ds[index]
    nmax = 90

    H = np.zeros((nmax + 1, nmax + 1))
    G = np.zeros((nmax + 1, nmax + 1))

    G[np.triu_indices(nmax + 1)] = arr[:arr.shape[0]//2]
    H[np.triu_indices(nmax + 1)] = arr[arr.shape[0]//2:]

    G = G.T 
    H = H.T
    
    return G, H, nmax

In [3]:
dataset_path = '/home/ubuntu/CoronalFieldExtrapolation/CoronalFieldExtrapolation_train/'
G, H, nmax = read_sh_coefficients(dataset_path, 900)

print(G[:3, :3])

[[ 2.40144455e-08  0.00000000e+00  0.00000000e+00]
 [ 1.89641739e+02  2.98057556e+00  0.00000000e+00]
 [ 3.29200935e+01  1.04706211e+01 -5.99548378e+01]]


In [4]:
sh = visualization_tools.SHVisualizer(G, H)
sh.visualize_field_lines(grid_density=20, r=1.1, closed_only=False)