In [1]:
import numpy as np
from dataset import CoronalFieldDataset
import visualization_tools

/home/ubuntu/micromamba/envs/coronal-diffusion-modeling/lib/python3.12/site-packages/ai/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources


# Test Visualization Tools

In [2]:

def read_sh_coefficients(dataset_path, index):
    ds = CoronalFieldDataset(dataset_path)
    arr = ds[index]
    nmax = 90

    H = np.zeros((nmax + 1, nmax + 1))
    G = np.zeros((nmax + 1, nmax + 1))

    G[np.triu_indices(nmax + 1)] = arr[:arr.shape[0]//2]
    H[np.triu_indices(nmax + 1)] = arr[arr.shape[0]//2:]

    G = G.T 
    H = H.T
    
    return G, H, nmax

In [3]:
dataset_path = '/home/ubuntu/CoronalFieldExtrapolation/CoronalFieldExtrapolation_train/'
G, H, nmax = read_sh_coefficients(dataset_path, 100)

print(G[:3, :3])

[[ 1.21645499e-07  0.00000000e+00  0.00000000e+00]
 [ 1.93229996e+02 -5.00076580e+00  0.00000000e+00]
 [ 2.38088989e+01  3.43944511e+01  3.55876427e+01]]


In [ ]:
sh = visualization_tools.SHVisualizer(G, H)
sh.visualize_field_lines(grid_density=10, r=1.1, closed_only=False)