In [1]:
import numpy as np
from dataset import CoronalFieldDataset
import visualization_tools

/home/ubuntu/micromamba/envs/coronal-diffusion-modeling/lib/python3.12/site-packages/ai/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources


# Test Visualization Tools

In [2]:

def read_sh_coefficients(dataset_path, index):
    ds = CoronalFieldDataset(dataset_path)
    arr = ds[index]
    nmax = 90

    H = np.zeros((nmax + 1, nmax + 1))
    G = np.zeros((nmax + 1, nmax + 1))

    G[np.triu_indices(nmax + 1)] = arr[:arr.shape[0]//2]
    H[np.triu_indices(nmax + 1)] = arr[arr.shape[0]//2:]

    G = G.T 
    H = H.T
    
    return G, H, nmax

In [3]:
dataset_path = '/home/ubuntu/CoronalFieldExtrapolation/CoronalFieldExtrapolation_train/'
G, H, nmax = read_sh_coefficients(dataset_path, 500)

print(G[:3, :3])

[[ 2.96833434e-07  0.00000000e+00  0.00000000e+00]
 [ 7.25061798e+01  5.00041618e+01  0.00000000e+00]
 [-1.57815765e+02  2.93307819e+01 -2.27683334e+02]]


In [4]:
sh = visualization_tools.SHVisualizer(G, H)
sh.visualize_field_lines()